#!/usr/bin/env python3
"""
build_dashboard.py — sales dashboard / analytics builder using pandas + plotly.

Usage:
    python3 build_dashboard.py spec.json out.html

spec.json schema:
{
  "title": "Sales Dashboard - Q1 2026",
  "kpis": [{"label": "ARR", "value": "$4.2M", "delta": "+12%"}],
  "charts": [
    {
      "type": "bar"|"line"|"funnel"|"pie"|"scatter",
      "title": "...",
      "data_csv": "/path/to.csv",          # OR
      "data_inline": [{"x":"Jan","y":100}, ...],
      "x": "x", "y": "y",                    # column names
      "color": "category"                     # optional
    }
  ]
}
"""
import sys, os, json
from pathlib import Path

# ⭐ นโยบายฟอนต์มาจาก SSOT เดียว — ห้าม hard-code ชื่อฟอนต์ในไฟล์นี้ (V02R01 · 2026.08.04)
#   บั๊กที่แก้: CSS stack เดิมเป็นละตินล้วน (-apple-system,Segoe UI,Helvetica,Arial)
#   → ข้อความไทยตกไป fallback ของ browser ที่ไม่ชดเชยขนาด = ไทยเล็กกว่าอังกฤษทั้งหน้า
sys.path.insert(0, os.path.expanduser("~/.claude/agents/_lib"))
from font_policy import RAILS, rail_fallbacks   # noqa: E402

RAIL = os.environ.get("ICE_RAIL", "private")
if RAIL not in RAILS:
    RAIL = "private"
# ลำดับ: ฟอนต์ราง → fallback ตามลำดับใน font_policy (Leelawadee UI → Sukhumvit Set → Tahoma)
FONT_STACK = ", ".join([f"'{RAILS[RAIL]['font']}'"]
                       + [f"'{x}'" for x in rail_fallbacks(RAIL)]
                       + ["-apple-system", "'Segoe UI'", "sans-serif"])
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots


def kpi_html(kpis):
    if not kpis:
        return ""
    cards = []
    for k in kpis:
        delta = k.get("delta", "")
        cards.append(
            f'<div style="flex:1;padding:18px;background:#f7f9fc;border-radius:10px;'
            f'border:1px solid #e1e6ee;margin:6px;text-align:center;">'
            f'<div style="font-size:13px;color:#5a6573;">{k.get("label","")}</div>'
            f'<div style="font-size:30px;font-weight:700;color:#1f4e79;">{k.get("value","")}</div>'
            f'<div style="font-size:12px;color:#2e8540;">{delta}</div>'
            f'</div>'
        )
    return f'<div style="display:flex;flex-wrap:wrap;gap:6px;">{"".join(cards)}</div>'


def load_data(chart):
    if chart.get("data_csv"):
        return pd.read_csv(chart["data_csv"])
    return pd.DataFrame(chart.get("data_inline", []))


def chart_html(chart):
    df = load_data(chart)
    t = chart.get("type", "bar")
    title = chart.get("title", "")
    x = chart.get("x")
    y = chart.get("y")
    color = chart.get("color")
    if t == "bar":
        fig = px.bar(df, x=x, y=y, color=color, title=title)
    elif t == "line":
        fig = px.line(df, x=x, y=y, color=color, title=title, markers=True)
    elif t == "pie":
        fig = px.pie(df, names=x, values=y, title=title)
    elif t == "scatter":
        fig = px.scatter(df, x=x, y=y, color=color, title=title)
    elif t == "funnel":
        fig = go.Figure(go.Funnel(y=df[x], x=df[y]))
        fig.update_layout(title_text=title)
    else:
        fig = px.bar(df, x=x, y=y, title=title)
    # กราฟก็ต้องใช้ฟอนต์เดียวกัน — ไม่งั้น label ไทยในกราฟตกไป fallback คนละตัวกับตัวหน้า
    fig.update_layout(margin=dict(l=20, r=20, t=50, b=20), template="plotly_white",
                      font=dict(family=FONT_STACK))
    return fig.to_html(full_html=False, include_plotlyjs=False)


def build(spec_path, out_path):
    with open(spec_path) as f:
        spec = json.load(f)
    title = spec.get("title", "Sales Dashboard")
    kpi_block = kpi_html(spec.get("kpis", []))
    charts = "".join(f'<div style="margin:14px 0;">{chart_html(c)}</div>' for c in spec.get("charts", []))
    html = f"""<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><title>{title}</title>
<script src="https://cdn.plot.ly/plotly-2.32.0.min.js"></script>
<style>
  body{{font-family:{FONT_STACK};max-width:1200px;margin:24px auto;padding:0 16px;color:#222;}}
  h1{{color:#1f4e79;margin-bottom:6px;}}
  .meta{{color:#5a6573;font-size:13px;margin-bottom:18px;}}
</style>
</head><body>
<h1>{title}</h1>
<div class="meta">Generated by sales-dashboard-agent</div>
{kpi_block}
{charts}
</body></html>"""
    Path(out_path).write_text(html, encoding="utf-8")
    print(f"OK: wrote {out_path}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("usage: build_dashboard.py spec.json out.html", file=sys.stderr)
        sys.exit(2)
    build(sys.argv[1], sys.argv[2])
